# Generated by Django 3.2.3 on 2021-06-06 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('Cid', models.BigAutoField(primary_key=True, serialize=False)),
                ('Cname', models.CharField(max_length=128, unique=True)),
                ('Cdescription', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('Lid', models.BigAutoField(primary_key=True, serialize=False)),
                ('Lkey', models.CharField(max_length=6, unique=True)),
                ('Lname', models.CharField(max_length=64)),
                ('Lplayerlimit', models.PositiveSmallIntegerField(default=8)),
                ('Lquestionamount', models.PositiveSmallIntegerField(default=20)),
                ('Ltimeamount', models.PositiveSmallIntegerField(default=20)),
                ('Lprivate', models.BooleanField(default=False)),
                ('Lpassword', models.CharField(help_text='250000 iterations of SHA256', max_length=128, null=True)),
                ('Lauthtoken', models.CharField(help_text='Auth token for Link join. Should be contained in link', max_length=64, null=True)),
                ('Lcreated', models.DateTimeField(auto_now=True)),
                ('Lstarted', models.BooleanField(default=False)),
                ('LcurrentQuestion', models.PositiveIntegerField(default=0)),
                ('LcurrentCorrect', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LobbyType',
            fields=[
                ('LTid', models.SmallAutoField(primary_key=True, serialize=False)),
                ('LTname', models.CharField(max_length=32)),
                ('LTdescription', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('Pid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Pdescription', models.CharField(blank=True, max_length=256, null=True)),
                ('Pcontent', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('QTid', models.SmallAutoField(primary_key=True, serialize=False)),
                ('QTname', models.CharField(max_length=32)),
                ('QTdescription', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ReportType',
            fields=[
                ('RTid', models.SmallAutoField(primary_key=True, serialize=False)),
                ('RTname', models.CharField(max_length=32, unique=True)),
                ('RTdescription', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('Sid', models.BigAutoField(primary_key=True, serialize=False)),
                ('Swon', models.PositiveIntegerField(db_index=True, default=0)),
                ('Slost', models.PositiveIntegerField(db_index=True, default=0)),
                ('Qcorrect', models.PositiveIntegerField(db_index=True, default=0)),
                ('Qwrong', models.PositiveIntegerField(db_index=True, default=0)),
                ('Uid', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('STid', models.AutoField(primary_key=True, serialize=False)),
                ('Sdescription', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='UserPrivate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UPprivate', models.BooleanField(default=False)),
                ('UPregistered', models.BooleanField(default=True)),
                ('UPlastseen', models.BooleanField(default=True)),
                ('Uid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pid', models.OneToOneField(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='kwiss_it.picture')),
                ('Uid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserLastSeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LastSeen', models.DateTimeField(auto_now=True)),
                ('Uid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Udescription', models.CharField(max_length=1000)),
                ('Uid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('Rid', models.BigAutoField(primary_key=True, serialize=False)),
                ('RefId', models.PositiveIntegerField(db_index=True)),
                ('Rdescription', models.CharField(max_length=1000, null=True)),
                ('RTid', models.ForeignKey(help_text='ReportType ID', on_delete=django.db.models.deletion.RESTRICT, to='kwiss_it.reporttype')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('Qid', models.BigAutoField(primary_key=True, serialize=False)),
                ('Qtext', models.CharField(max_length=256)),
                ('Qplaycount', models.PositiveIntegerField(default=0)),
                ('Cid', models.ForeignKey(default=1, help_text='Category ID', on_delete=django.db.models.deletion.SET_DEFAULT, to='kwiss_it.category')),
                ('Pid', models.ForeignKey(blank=True, help_text='Picture ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='kwiss_it.picture')),
                ('QTid', models.ForeignKey(help_text='QuestionType ID', on_delete=django.db.models.deletion.RESTRICT, to='kwiss_it.questiontype')),
                ('STid', models.ForeignKey(default=1, help_text='State ID', on_delete=django.db.models.deletion.RESTRICT, to='kwiss_it.state')),
                ('Uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LobbyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LPready', models.BooleanField(default=False)),
                ('LPLastHeartbeat', models.DateTimeField(auto_now_add=True)),
                ('LPScore', models.IntegerField(default=0)),
                ('LPStreak', models.IntegerField(default=0)),
                ('LPlastaddition', models.IntegerField(default=0)),
                ('LPdeviation', models.BigIntegerField(default=0)),
                ('LPwasdeviation', models.BooleanField(default=False)),
                ('LPquestionanswered', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='kwiss_it.question')),
                ('Lid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kwiss_it.lobby')),
                ('Uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lobby',
            name='Ltype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='kwiss_it.lobbytype'),
        ),
        migrations.AddField(
            model_name='lobby',
            name='Uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DiscordRole',
            fields=[
                ('DRid', models.BigAutoField(primary_key=True, serialize=False)),
                ('DRkey', models.CharField(help_text='Generated UUID4', max_length=36, unique=True)),
                ('DiscordName', models.CharField(help_text="User's Discord Name in base64url", max_length=256)),
                ('Deprecated', models.BooleanField(default=False)),
                ('Uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='STid',
            field=models.ForeignKey(default=1, help_text='State ID', on_delete=django.db.models.deletion.RESTRICT, to='kwiss_it.state'),
        ),
        migrations.AddField(
            model_name='category',
            name='Uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Score_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cid', models.ForeignKey(help_text='Category ID', on_delete=django.db.models.deletion.CASCADE, to='kwiss_it.category')),
                ('Sid', models.ForeignKey(help_text='Score ID', on_delete=django.db.models.deletion.CASCADE, to='kwiss_it.score')),
            ],
            options={
                'unique_together': {('Sid', 'Cid')},
            },
        ),
        migrations.CreateModel(
            name='QuestionVotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.SmallIntegerField(default=0)),
                ('Qid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kwiss_it.question')),
                ('Uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('Qid', 'Uid')},
            },
        ),
        migrations.CreateModel(
            name='LobbyQuestions',
            fields=[
                ('LQid', models.BigAutoField(primary_key=True, serialize=False)),
                ('Lid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kwiss_it.lobby')),
                ('Qid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kwiss_it.question')),
            ],
            options={
                'unique_together': {('Lid', 'Qid')},
            },
        ),
        migrations.CreateModel(
            name='LobbyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kwiss_it.category')),
                ('Lid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kwiss_it.lobby')),
            ],
            options={
                'unique_together': {('Lid', 'Cid')},
            },
        ),
        migrations.CreateModel(
            name='CategoryVotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.SmallIntegerField(default=0)),
                ('Cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kwiss_it.category')),
                ('Uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('Cid', 'Uid')},
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Anum', models.SmallIntegerField()),
                ('Atext', models.CharField(max_length=64)),
                ('Acorrect', models.BooleanField(default=0)),
                ('Qid', models.ForeignKey(help_text='Question ID', on_delete=django.db.models.deletion.CASCADE, to='kwiss_it.question')),
            ],
            options={
                'unique_together': {('Qid', 'Anum')},
            },
        ),
    ]
