# Generated by Django 3.2.3 on 2021-06-07 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kwiss_it', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='Cid',
            field=models.ForeignKey(default=1, help_text='Category ID', on_delete=django.db.models.deletion.CASCADE, to='kwiss_it.category'),
        ),
    ]
