# Generated by Django 3.2.3 on 2021-05-17 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kwiss_it', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='Qid',
            field=models.ForeignKey(help_text='Question ID', on_delete=django.db.models.deletion.CASCADE, to='kwiss_it.question'),
        ),
        migrations.AlterField(
            model_name='category',
            name='STid',
            field=models.ForeignKey(default=0, help_text='State ID', on_delete=django.db.models.deletion.RESTRICT, to='kwiss_it.state'),
        ),
        migrations.AlterField(
            model_name='question',
            name='Cid',
            field=models.ForeignKey(default=0, help_text='Category ID', on_delete=django.db.models.deletion.SET_DEFAULT, to='kwiss_it.category'),
        ),
        migrations.AlterField(
            model_name='question',
            name='Pid',
            field=models.ForeignKey(blank=True, help_text='Picture ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='kwiss_it.picture'),
        ),
        migrations.AlterField(
            model_name='question',
            name='QTid',
            field=models.ForeignKey(help_text='QuestionType ID', on_delete=django.db.models.deletion.RESTRICT, to='kwiss_it.questiontype'),
        ),
        migrations.AlterField(
            model_name='question',
            name='STid',
            field=models.ForeignKey(default=0, help_text='State ID', on_delete=django.db.models.deletion.RESTRICT, to='kwiss_it.state'),
        ),
        migrations.AlterField(
            model_name='report',
            name='RTid',
            field=models.ForeignKey(help_text='ReportType ID', on_delete=django.db.models.deletion.RESTRICT, to='kwiss_it.reporttype'),
        ),
        migrations.AlterField(
            model_name='report',
            name='RefId',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='Rid',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reporttype',
            name='RTid',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='score_category',
            name='Cid',
            field=models.ForeignKey(help_text='Category ID', on_delete=django.db.models.deletion.CASCADE, to='kwiss_it.category'),
        ),
        migrations.AlterField(
            model_name='score_category',
            name='Sid',
            field=models.ForeignKey(help_text='Score ID', on_delete=django.db.models.deletion.CASCADE, to='kwiss_it.score'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Pid',
            field=models.ForeignKey(blank=True, help_text='Picture ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='kwiss_it.picture'),
        ),
        migrations.CreateModel(
            name='DiscordRole',
            fields=[
                ('DRid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('DRkey', models.CharField(help_text='Generated UUID4', max_length=36, unique=True)),
                ('DiscordName', models.CharField(help_text="User's Discord Name in base64url", max_length=256)),
                ('Deprecated', models.BooleanField(default=False)),
                ('Uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kwiss_it.user')),
            ],
        ),
    ]
