# Generated by Django 3.2.3 on 2021-05-27 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kwiss_it', '0003_auto_20210527_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdescription',
            name='Uid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userpicture',
            name='Pid',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='kwiss_it.picture'),
        ),
        migrations.AlterField(
            model_name='userpicture',
            name='Uid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
