# Generated by Django 3.2.3 on 2021-05-29 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kwiss_it', '0004_auto_20210527_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLastSeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LastSeen', models.DateTimeField(auto_now=True)),
                ('Uid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
