# Generated by Django 3.2.3 on 2021-05-31 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwiss_it', '0005_userlastseen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score_category',
            name='SCplaycount',
        ),
        migrations.AddField(
            model_name='question',
            name='Qplaycount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='Qcorrect',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='Qwrong',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
