# Generated by Django 3.2.3 on 2021-05-31 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwiss_it', '0006_auto_20210531_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='Rdescription',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='Anum',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='Cid',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='discordrole',
            name='DRid',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='Qid',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='questiontype',
            name='QTid',
            field=models.SmallAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='Rid',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reporttype',
            name='RTid',
            field=models.SmallAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='score',
            name='Sid',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='state',
            name='STid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
