# Generated by Django 3.2.3 on 2021-05-31 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwiss_it', '0007_auto_20210531_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontype',
            name='QTname',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
