# Generated by Django 3.2.3 on 2021-06-01 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kwiss_it', '0008_questiontype_qtname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('Lid', models.BigAutoField(primary_key=True, serialize=False)),
                ('Lname', models.CharField(max_length=64)),
                ('Lprivate', models.BooleanField(default=False)),
                ('Lpassword', models.CharField(help_text='250000 iterations of SHA256', max_length=128)),
                ('Lauthtoken', models.CharField(help_text='Auth token for Link join. Should be contained in link', max_length=64)),
                ('Lcreated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LobbyType',
            fields=[
                ('LTid', models.SmallAutoField(primary_key=True, serialize=False)),
                ('LTname', models.CharField(max_length=32)),
                ('LTdescription', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='score',
            name='Uid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Lobby_Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LPwon', models.BooleanField(default=False)),
                ('Lid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kwiss_it.lobby')),
                ('Uid', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lobby',
            name='Ltype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='kwiss_it.lobbytype'),
        ),
    ]
