# Generated by Django 3.2.3 on 2021-06-02 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kwiss_it', '0009_auto_20210601_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='Lcurrentplayer',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lobby',
            name='Lplayerlimit',
            field=models.PositiveSmallIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='lobby',
            name='Uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='Lauthtoken',
            field=models.CharField(help_text='Auth token for Link join. Should be contained in link', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='Lpassword',
            field=models.CharField(help_text='250000 iterations of SHA256', max_length=128, null=True),
        ),
        migrations.DeleteModel(
            name='Lobby_Player',
        ),
    ]
