# Generated by Django 3.2.3 on 2021-06-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwiss_it', '0012_auto_20210602_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprivate',
            name='UPlastseen',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprivate',
            name='UPprivate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprivate',
            name='UPregistered',
            field=models.BooleanField(default=True),
        ),
    ]
