# Generated by Django 3.2.3 on 2021-06-02 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kwiss_it', '0013_auto_20210602_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='Lstarted',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='LobbyQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kwiss_it.lobby')),
                ('Qid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kwiss_it.question')),
            ],
            options={
                'unique_together': {('Lid', 'Qid')},
            },
        ),
    ]
