# Generated by Django 3.2.3 on 2021-06-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwiss_it', '0014_auto_20210602_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='Lplayerready',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
