# Generated by Django 3.2.3 on 2021-06-02 21:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kwiss_it', '0016_auto_20210602_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobbyplayer',
            name='LPLastHeartbeat',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
