# Generated by Django 3.2.3 on 2021-06-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwiss_it', '0017_lobbyplayer_lplastheartbeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='Lkey',
            field=models.CharField(default=123456, max_length=6, unique=True),
            preserve_default=False,
        ),
    ]
