# Generated by Django 3.2.3 on 2021-06-03 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwiss_it', '0018_lobby_lkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Cname',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
