# Generated by Django 3.2.3 on 2021-06-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwiss_it', '0019_alter_category_cname'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='Lquestionamount',
            field=models.PositiveSmallIntegerField(default=20),
        ),
    ]
