# Generated by Django 3.2.3 on 2021-06-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwiss_it', '0020_lobby_lquestionamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='Ltimeamount',
            field=models.PositiveSmallIntegerField(default=20),
        ),
    ]
