# Generated by Django 3.2.3 on 2021-06-03 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kwiss_it', '0021_lobby_ltimeamount'),
    ]

    operations = [
        migrations.CreateModel(
            name='LobbyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kwiss_it.category')),
                ('Lid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kwiss_it.lobby')),
            ],
            options={
                'unique_together': {('Lid', 'Cid')},
            },
        ),
    ]
