# Generated by Django 3.2.3 on 2021-06-04 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kwiss_it', '0022_lobbycategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='testtest',
            fields=[
                ('Tid', models.BigAutoField(primary_key=True, serialize=False)),
                ('Lid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kwiss_it.lobby')),
            ],
        ),
    ]
