# Generated by Django 3.2.3 on 2021-06-04 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kwiss_it', '0023_testtest'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtest',
            name='Did',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='kwiss_it.discordrole'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testtest',
            name='Uid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testtest',
            name='Lid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kwiss_it.lobby'),
        ),
    ]
