# Generated by Django 3.2.3 on 2021-06-04 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kwiss_it', '0025_auto_20210604_1337'),
    ]

    operations = [
        migrations.DeleteModel(
            name='testtest',
        ),
    ]
