# Generated by Django 3.2.3 on 2021-06-04 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kwiss_it', '0028_alter_lobbyplayer_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='LobbyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LPready', models.BooleanField(default=False)),
                ('LPLastHeartbeat', models.DateTimeField(auto_now_add=True)),
                ('LPScore', models.IntegerField(default=0)),
                ('LPStreak', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='lobby',
            name='LcurrentCorrect',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lobby',
            name='LcurrentQuestion',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='LobbyPlayer',
        ),
        migrations.AddField(
            model_name='lobbyuser',
            name='Lid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kwiss_it.lobby'),
        ),
        migrations.AddField(
            model_name='lobbyuser',
            name='Uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
