# Generated by Django 3.2.3 on 2021-06-04 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwiss_it', '0029_auto_20210604_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lobbyquestions',
            name='id',
        ),

    ]
