# Generated by Django 3.2.3 on 2021-06-04 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwiss_it', '0030_auto_20210604_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobbyquestions',
            name='LQid',
            field=models.BigAutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
