# Generated by Django 3.2.3 on 2021-06-06 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kwiss_it', '0031_lobbyquestions_lqid'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobbyuser',
            name='LPlastaddition',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='Qmoddownvotes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='Qmodupvotes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='QuestionVotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.SmallIntegerField(default=0)),
                ('Qid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kwiss_it.question')),
                ('Uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('Qid', 'Uid')},
            },
        ),
        migrations.CreateModel(
            name='CategoryVotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.SmallIntegerField(default=0)),
                ('Cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kwiss_it.category')),
                ('Uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('Cid', 'Uid')},
            },
        ),
    ]
