# Generated by Django 3.2.3 on 2021-06-06 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kwiss_it', '0032_auto_20210606_0159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='Cdownvotes',
        ),
        migrations.RemoveField(
            model_name='category',
            name='Cupvotes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='Qdownvotes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='Qmoddownvotes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='Qmodupvotes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='Qupvotes',
        ),
        migrations.AddField(
            model_name='lobbyuser',
            name='LPdeviation',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lobbyuser',
            name='LPquestionanswered',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='kwiss_it.question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lobbyuser',
            name='LPwasdeviation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lobbyuser',
            name='LPStreak',
            field=models.IntegerField(default=0),
        ),
    ]
