# Generated by Django 3.2.3 on 2021-06-06 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kwiss_it', '0033_auto_20210606_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobbyuser',
            name='LPquestionanswered',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='kwiss_it.question'),
        ),
    ]
